# Generated by Django 5.2.17 on 2026-09-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0002_alter_client_thumbnail'),
        ('Workspaces', '0002_remove_workspace_unique_workspace_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#2563eb', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_archived', models.BooleanField(default=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clients.client')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Workspaces.workspace')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workspace', 'name'), name='unique_project_name_per_workspace')],
            },
        ),
    ]
