# Generated by Django 5.2.17 on 2026-09-08 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Workspaces', '0002_remove_workspace_unique_workspace_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#64748b', max_length=20)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='Workspaces.workspace')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workspace', 'name'), name='unique_tag_name_per_workspace')],
            },
        ),
    ]
