# Generated by Django 5.2.17 on 2026-09-07 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspace',
            name='unique_workspace_membership',
        ),
        migrations.RemoveConstraint(
            model_name='workspacemembership',
            name='unique_active_user_per_workspace',
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('owner', 'name'), name='unique_workspace_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'workspace'), name='unique_workspace_membership'),
        ),
    ]
