# Generated by Django 5.2.17 on 2026-09-07 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Workspaces', '0002_remove_workspace_unique_workspace_membership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='clients/')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Workspaces.workspace')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('workspace', 'name'), name='unique_client_name_per_workspace')],
            },
        ),
    ]
