# Generated by Django 5.2.17 on 2026-09-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='clients/'),
        ),
    ]
